/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include <stdint.h>
//
//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
#include "_delay_ms.h"
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "RCC_init.h"
#include "GPIO_init.h"
#include "FreeRTOS.h"
#include "task.h"

TaskHandle_t	xLedOnTaskHandle;
TaskHandle_t	xButtonOnTaskHandle;

void	vLedOnTask(void *pvParameter);
void	vButtonOnTask(void *pvParameter);

u8 flag = 0;
u8 read;
int main(void)
{
	M_RCC_void_SysClkInit();
	M_RCC_void_EnablePerClk(RCC_APB2, 2);
	M_GPIO_void_SetPinDir(PORTA_ID, PIN1_ID, OUT_50MHZ_PP);
	M_GPIO_void_SetPinDir(PORTA_ID, PIN0_ID, IN_PULL_UP_DOWN);
	M_GPIO_void_SetPinValue(PORTA_ID, PIN1_ID, HIGH);

	   xTaskCreate(     vLedOnTask , "LED On", 128, NULL , 1 , &xLedOnTaskHandle);
	   xTaskCreate(     vButtonOnTask , "Button On", 128, NULL , 2 , &xButtonOnTaskHandle);
	   vTaskStartScheduler();
    /* Loop forever */
	for(;;);
}

void	vLedOnTask(void *pvParameter)
{
	for(;;)
	{
		vTaskDelay(200);
		if(flag == 1)
		{
			M_GPIO_void_TogPin(PORTA_ID, PIN1_ID);
			flag = 0;
		}
	}
}
void	vButtonOnTask(void *pvParameter)
{
	for(;;)
	{
		vTaskDelay(100);
		M_GPIO_void_GetPinValue(PORTA_ID, PIN0_ID, &read);
		if(read == 1)
		{
			flag = 1;
		}
	}
}
